#!/bin/zsh

# ls
alias ls='exa --color=auto --group-directories-first'
alias la='ls -a'
alias l='ls -la'
alias ll='ls -l'
alias lt='ls -Ta'
alias llt='ls -T'

# color
alias ip='ip --color=auto'
alias diff='diff --color=auto'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# renames
alias v='nvim'
alias pdf='zathura'
alias img='sxiv'
alias d='disown'

# clipboard
alias xclip='xclip -selection clipboard'

# dotfiles
alias dot="git --git-dir=${XDG_DATA_HOME:-"$HOME/.local/share"}/dotfiles --work-tree="$HOME""

# updates
alias upd='paru -Syyu --devel --noconfirm; paru -c --noconfirm; paru -Sc --noconfirm'
alias updm='sudo reflector --country Germany --latest 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist --verbose; upd'

# suckless
alias i='sudo make clean install; sudo make clean'
alias ch='nvim config.def.h'

# note
alias note="cd $HOME/notes; nvim"

# latex
alias newmain="cp $HOME/templ/latex/doc/main.tex ."
alias newpres="cp $HOME/templ/latex/pres/main.tex ."

# rust
alias c='cargo'
