#!/bin/zsh

alias v='nvim'

alias ls='exa --color=auto --group-directories-first'
alias la='ls -a'
alias l='ls -la'
alias ll='ls -l'
alias lt='ls -Ta'
alias llt='ls -T'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias pdf='zathura'
alias img='sxiv'

# copy and paste to clipboard
alias xclip='xclip -selection clipboard'

# dotfiles
alias dot="git --git-dir=${XDG_DATA_HOME:-"$HOME/.local/share"}/dotfiles --work-tree="$HOME""

# updates
alias upd='paru -Syyu --devel --noconfirm; paru -c --noconfirm; paru -Sc --noconfirm'
alias updm='sudo reflector --country Germany --latest 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist --verbose; upd'

# suckless
alias i='sudo make clean install; sudo make clean'
alias c='nvim config.def.h'

# note
alias note="cd $HOME/Notes; nvim"

# latex
alias newmain="cp $HOME/Templates/LaTeX/Document/main.tex ."
alias newshort="cp $HOME/Templates/LaTeX/Document/short.tex main.tex"
alias newpres="cp $HOME/Templates/LaTeX/Presentation/* ."
