#!/bin/zsh

# disable <c-s> and <c-q>
stty stop undef
stty start undef

# edit the current command in vim with <c-e>
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^e' edit-command-line

# new st window in current directory
bindkey -s '^n' 'st 2> /dev/null & disown\n'

# use lf to switch directories with <c-o>
lfcd()
{
	temp="$(mktemp)"
	lf -last-dir-path="$temp" "$@"
	if [[ -f $temp ]]
	then
		dir="$(cat "$temp")"
		rm -f "$temp" >/dev/null
		[[ -d $dir && $dir != $(pwd) ]] && cd "$dir"
	fi
	clear
}
bindkey -s '^o' 'lfcd\n'
