#!/bin/zsh

# aliases
alias vim='nvim'

alias ls='exa --color=auto --group-directories-first'
alias ll='ls -l'
alias l='ls -la'
alias llt='ls -T'
alias lt='ls -aT'

alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

alias dotfiles="git --git-dir=${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles/ --work-tree=$HOME"

alias i='sudo make clean install; sudo make clean'
alias c='vim config.def.h'

alias pdf='zathura'
alias img='sxiv'

alias upd='paru -Syyu --devel --noconfirm; paru -Rns $(paru -Qqtd) --noconfirm; paru -Sc --noconfirm'
alias updm='sudo reflector --country Germany --latest 100 --sort rate --save /etc/pacman.d/mirrorlist --verbose; upd'

alias newmain="cp $HOME/Templates/LaTeX/main.tex ."
alias newshort="cp $HOME/Templates/LaTeX/short.tex ."
