#!/bin/zsh

# aliases
alias ls='exa --color=auto --group-directories-first'
alias lt='ls -aT'
alias ll='ls -l'
alias l='ls -la'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias vim='nvim'

alias dotfiles="git --git-dir=${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/ --work-tree=$HOME"

alias i='sudo make clean install; sudo make clean'
alias c='vim config.def.h'

alias pdf='zathura'
alias img='sxiv'

alias upd='sudo reflector --country Germany --latest 100 --protocol https --sort rate --save /etc/pacman.d/mirrorlist --verbose; yay -Syyu --devel --noconfirm; yay -Yc --noconfirm; yay -Sc --noconfirm'
