#!/bin/zsh

# cursor shapes for vim modes
function zle-keymap-select {
	case "$KEYMAP" in
		vicmd) echo -ne "$cursor_block" ;;
		viins|main) echo -ne "$cursor_beam" ;;
	esac
}
zle -N zle-keymap-select


function precmd {
	# set terminal title to current working directory
	print -Pn '\e]0;%~\a'
}

function preexec {
	# set terminal title to current command
	print -Pn "\e]0;$1\a"

	# reset cursor shape
	echo -ne "$cursor_beam"
}

zle-line-init() {
	# reset cursor shape
	echo -ne "$cursor_beam"
}
zle -N zle-line-init

get_xresource() {
	xrdb -query | grep $1 | awk '{print $2}'
}
