#!/bin/zsh

# disable <c-s> and <c-q>
stty stop undef
stty start undef

# use lf to switch directories with <c-o>
lfcd() {
	tmp="$(mktemp)"
	lf -last-dir-path="$tmp" "$@"
	if [[ -f $tmp ]]
	then
		dir="$(cat "$tmp")"
		rm -f "$tmp" >/dev/null
		[[ -d $dir ]] && [[ $dir != $(pwd) ]] && cd "$dir"
	fi
	clear
}
bindkey -s '^o' 'lfcd\n'
