#!/bin/zsh

# history settings
setopt hist_expire_dups_first hist_reduce_blanks

# enable comments
setopt interactive_comments

# vim mode
bindkey -v
export KEYTIMEOUT=1

# prompt variables
autoload -Uz colors && colors
PS1='%B%F{yellow}%n%b%f@%B%F{magenta}%M %F{blue}%~ %(?.%F{green}.%F{red})$%b%f '
PS2=''
