#!/bin/sh

# start the scripts in xinitrc.d
if [ -d '/etc/X11/xinit/xinitrc.d' ]
then
	for f in '/etc/X11/xinit/xinitrc.d/'?*'.sh'
	do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# start the session
lxsession -a &

# start the compositor
picom &

# set the wallpaper
#xwallpaper --zoom "$HOME/.config/wallpaper.jpg" &
hsetroot -solid '#000000' &

# start redshift
redshift -O 3500

# start dwmblocks
dwmblocks &

# start dunst for notifications
dunst &

# bluetooth applet
blueman-applet &

# enable automatic locking
xautolock -time 5 -locker slock &

# remove the mouse when idle
unclutter &

# set character repetition rate
xset r rate 300 50 &

# start dwm
while true
do
	dwm >/dev/null 2>&1
done
exec dwm
