#!/bin/sh

userresources="${XDG_CONFIG_HOME:-$HOME/.config}/.Xresources"
usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}/.Xmodmap"
sysresources="/etc/X11/xinit/.Xresources"
sysmodmap="/etc/X11/xinit/.Xmodmap"

# merge the defaults and keymaps
if [ -f "$sysresources" ]
then
    xrdb -merge "$sysresources"
fi

if [ -f "$sysmodmap" ]
then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]
then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]
then
    xmodmap "$usermodmap"
fi

# start the programs in the /etc/X11/xinit/xinitrc.d directory
if [ -d "/etc/X11/xinit/xinitrc.d" ]
then
	for f in "/etc/X11/xinit/xinitrc.d/?*.sh"
	do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# start the compositor
picom &

# set the wallpaper
#xwallpaper --zoom $HOME/.config/wallpaper.jpg &
hsetroot -solid "#000000" &

# start the status monitor
slstatus &

# enable automatically locking the computer with slock after 5min
xautolock -time 5 -locker slock &

# start unclutter to remove the mouse when idle
unclutter &

# start redshift
redshift &

# enable character repeatition with a delay of 200ms and a rate of 50ms
xset r rate 200 50 &

# start dwm
while true
do
	dwm >/dev/null 2>&1
done
exec dwm
