#!/bin/sh

# execute scripts in xinitrc.d
if [ -d '/etc/X11/xinit/xinitrc.d' ]
then
	for f in '/etc/X11/xinit/xinitrc.d/'?*'.sh'
	do
		[[ -x $f ]] && . "$f"
	done
	unset f
fi

# session polkit
lxpolkit &

# x resources
[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources ]] && xrdb -merge -I${XDG_CONFIG_HOME:-$HOME/.config}/X11 ${XDG_CONFIG_HOME:-$HOME/.config}/X11/Xresources

# compositor
picom &

# wallpaper
#xwallpaper --zoom "$HOME/.config/wallpaper.jpg" &
hsetroot -solid '#000000' &

# blue light filter
redshift -O 3500

# status bar
dwmblocks &

# notifications
dunst &

# bluetooth
blueman-applet &

# automatic screen locking
xautolock -time 30 -locker slock &

# remove mouse when idle
unclutter &

# character repetition rate
xset r rate 300 50 &

# start dwm
while true
do
	dwm >/dev/null 2>&1
done
exec dwm
