require 'settings'
require 'install_packer'
require 'colorscheme'
require 'plugins'
require 'lsp'
require 'completions'
require 'spelling'
vim.cmd 'source ~/.config/nvim/vim/mappings.vim'
vim.cmd 'source ~/.config/nvim/vim/autocommands.vim'
